### ISSUE TITLE
Incompatibility with newest (25.3.0) kubernetes package

### ISSUE THREAD

**Issue by ecklm** [devopsspiral/KubeLibrary#117]
Today, the kubernetes python library version 25.3.0 was released and it must have broken the API. Maybe a beta API was dropped.

I see the following error message in our integration tests:

```
Error in file '/path/to/kube.common.resource' on line 7: Initializing library 'KubeLibrary' with no arguments failed: AttributeError: module 'kubernetes.client' has no attribute 'BatchV1beta1Api' Traceback (most recent call last):   File "/usr/local/lib/python3.10/site-packages/KubeLibrary/KubeLibrary.py", line 96, in __init__     self.reload_config(kube_config=kube_config, context=context, api_url=api_url, bearer_token=bearer_token,   File "/usr/local/lib/python3.10/site-packages/KubeLibrary/KubeLibrary.py", line 263, in reload_config     self._add_api('batchv1_beta1', client.BatchV1beta1Api) AttributeError: module 'kubernetes.client' has no attribute 'BatchV1beta1Api'
--
```

Python package versions:
* kubernetes: 25.3.0
* robotframework-kubelibrary: 0.7.0

**Comment by m-wcislo** [comment]
Hi,
Yeah thanks for pointing it out. I'm working on CI fix that should cover this #116

**Comment by m-wcislo** [comment]
Hi,
Please take a look at v0.8.0

**Comment by ecklm** [comment]
Hi,

It seems to be working, thanks!
